all:
  children:
    aruba_distribution_switches:
      children:
        distswitch_N:
          hosts:
            aruba_N1:
              ansible_host: 10.2.127.1
        distswitch_Dorms:
          hosts:
            aruba_D1:
              ansible_host: 10.16.127.1
    
    aruba_access_switches:
      children:
        aruba_switches_N:
          hosts:
            aruba_N11:
              ansible_host: 10.2.127.11
            aruba_N12:
              ansible_host: 10.2.127.12
            aruba_N13:
              ansible_host: 10.2.127.13
            aruba_N14:
              ansible_host: 10.2.127.14
            aruba_N15:
              ansible_host: 10.2.127.15
            aruba_N16:
              ansible_host: 10.2.127.16
            aruba_N17:
              ansible_host: 10.2.127.17
            aruba_N18:
              ansible_host: 10.2.127.18
        aruba_switch_Dorms:
          hosts:
            aruba_FH1:
              ansible_host: 10.16.127.11
            aruba_FH2:
              ansible_host: 10.16.127.12
            aruba_FH3:
              ansible_host: 10.16.127.13
            aruba_FH4:
              ansible_host: 10.16.127.14
            aruba_FH5:
              ansible_host: 10.16.127.15
            aruba_FH6:
              ansible_host: 10.16.127.16
            aruba_FH7:
              ansible_host: 10.16.127.17
            aruba_food_court:
              ansible_host: 10.16.127.18
            aruba_GYM:
              ansible_host: 10.16.127.19
    
    aruba_controllers:
      hosts:
        MC-MAster:
          ansible_host: 10.1.126.50

  vars:
    ansible_connection: network_cli
    ansible_network_os: aruba
    ansible_user: ansibleadmin
    ansible_password: "{{ aruba_password }}"
    ansible_become: yes
    ansible_become_method: enable
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
