---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/awx-ee:latest'

dependencies:
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend:
    - RUN pip3 install --upgrade pip setuptools
  append:
    - RUN echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config
    - RUN echo "UserKnownHostsFile /dev/null" >> /etc/ssh/ssh_config
    - RUN echo "Host *" >> /etc/ssh/ssh_config
    - RUN echo "    KexAlgorithms +diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group-exchange-sha1" >> /etc/ssh/ssh_config
    - RUN echo "    HostKeyAlgorithms +ssh-rsa" >> /etc/ssh/ssh_config
    - RUN echo "    PubkeyAcceptedAlgorithms +ssh-rsa" >> /etc/ssh/ssh_config