---
# Playbook to backup configurations from Aruba switches using raw CLI commands
- name: Backup Aruba switch configurations
  hosts: all
  gather_facts: no
  
  vars:
    backup_path: "/var/lib/awx/projects/backups"
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
  
  tasks:
    - name: Create backup directory if it doesn't exist
      delegate_to: localhost
      file:
        path: "{{ backup_path }}"
        state: directory
      run_once: true
      
    - name: Create device-specific backup directory
      delegate_to: localhost
      file:
        path: "{{ backup_path }}/{{ inventory_hostname }}"
        state: directory
        
    - name: Fetch running configuration
      cli_command:
        command: "show running-config"
      register: config_output
      ignore_errors: yes
      
    - name: Save configuration to file
      delegate_to: localhost
      copy:
        content: "{{ config_output.stdout | default('Error retrieving configuration') }}"
        dest: "{{ backup_path }}/{{ inventory_hostname }}/{{ inventory_hostname }}_{{ timestamp }}.cfg"
      when: config_output is defined
      
    - name: Create inventory-specific directories
      delegate_to: localhost
      file:
        path: "{{ backup_path }}/groups/{{ group_names[0] | default('ungrouped') }}"
        state: directory
      run_once: false
      when: group_names | length > 0
      
    - name: Copy backups to inventory-specific folder
      delegate_to: localhost
      copy:
        src: "{{ backup_path }}/{{ inventory_hostname }}/{{ inventory_hostname }}_{{ timestamp }}.cfg"
        dest: "{{ backup_path }}/groups/{{ group_names[0] | default('ungrouped') }}/"
        remote_src: yes
      when: 
        - config_output is defined
        - group_names | length > 0
      ignore_errors: yes