---
- name: Backup Aruba Switch Configurations and show as Artifact
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Run show running-config on Aruba Switch
      community.network.aruba_command:
        commands:
          - show running-config
      register: running_config

    - name: Create Artifact directory (on Controller)
      delegate_to: localhost
      become: false
      run_once: true
      file:
        path: "/runner/artifacts/backup_configs"
        state: directory
        mode: '0755'

    - name: Save running-config to Artifact
      delegate_to: localhost
      become: false
      copy:
        content: "{{ running_config.stdout[0] }}"
        dest: "/runner/artifacts/backup_configs/{{ inventory_hostname }}_running-config.txt"
