---
# Playbook to configure Aruba switches using CLI commands
- name: Configure Aruba switches
  hosts: all
  gather_facts: no
  
  tasks:
    - name: Configure hostname 
      cli_command:
        command: "hostname {{ inventory_hostname }}"
      ignore_errors: yes
      
    - name: Configure management VLAN
      cli_command:
        command: "{{ item }}"
      loop:
        - "config"
        - "vlan 10"
        - "name Management"
        - "exit"
      ignore_errors: yes
      
    - name: Configure user VLAN
      cli_command:
        command: "{{ item }}"
      loop:
        - "config"
        - "vlan 20"
        - "name Users"
        - "exit"
      ignore_errors: yes
      
    - name: Configure server VLAN
      cli_command:
        command: "{{ item }}"
      loop:
        - "config"
        - "vlan 30"
        - "name Servers"
        - "exit"
      ignore_errors: yes
      
    - name: Configure NTP settings
      cli_command:
        command: "{{ item }}"
      loop:
        - "config"
        - "timesync ntp"
        - "ntp server 10.1.126.1"
        - "exit"
      ignore_errors: yes
      
    - name: Configure syslog server
      cli_command:
        command: "{{ item }}"
      loop:
        - "config"
        - "logging 10.1.126.5"
        - "exit"
      ignore_errors: yes
      
    - name: Save configuration
      cli_command:
        command: "write memory"
      ignore_errors: yes