---
################################################################################
# ARUBA SWITCH DYNAMIC INTERFACE CONFIGURATION PLAYBOOK
################################################################################
# Purpose: Automated configuration of Aruba switch ports based on:
#          - Room location mapping
#          - Device type (PC, printer, phone, etc.)
#          - VLAN assignments
#          - Port security settings
#
# This playbook handles 4 main configuration cases:
# CASE 1: Phone only - Tagged VLAN for VoIP
# CASE 2: Device only - Untagged VLAN for data devices  
# CASE 3: Device + Phone - Both untagged (device) and tagged (phone) VLANs
# CASE 4: Disabled port - Administrative down state
#
# Compatible with: ArubaOS-Switch (legacy and current versions)
################################################################################