---
# Playbook to gather facts from Aruba switches
- name: Gather facts from Aruba switches
  hosts: all
  gather_facts: no
  
  vars:
    output_path: "/var/lib/awx/projects/facts"
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
  
  tasks:
    - name: Create output directory if it doesn't exist
      delegate_to: localhost
      file:
        path: "{{ output_path }}"
        state: directory
      run_once: true
    
    - name: Gather facts from switches
      aruba_facts:
        gather_subset:
          - all
      register: switch_facts
    
    - name: Display switch model
      debug:
        msg: "Switch {{ inventory_hostname }} is a {{ switch_facts.ansible_facts.ansible_net_model }}"
    
    - name: Display firmware version
      debug:
        msg: "Switch {{ inventory_hostname }} is running firmware {{ switch_facts.ansible_facts.ansible_net_version }}"
    
    - name: Save facts to JSON file
      delegate_to: localhost
      copy:
        content: "{{ switch_facts | to_nice_json }}"
        dest: "{{ output_path }}/{{ inventory_hostname }}_facts_{{ timestamp }}.json"
    
    - name: Create inventory group directories
      delegate_to: localhost
      file:
        path: "{{ output_path }}/{{ group_names[0] }}"
        state: directory
      when: group_names | length > 0
    
    - name: Copy facts to inventory group folder
      delegate_to: localhost
      copy:
        src: "{{ output_path }}/{{ inventory_hostname }}_facts_{{ timestamp }}.json"
        dest: "{{ output_path }}/{{ group_names[0] }}/"
        remote_src: yes
      when: group_names | length > 0
    
    - name: Generate HTML report
      delegate_to: localhost
      template:
        src: templates/facts_report.j2
        dest: "{{ output_path }}/facts_report_{{ timestamp }}.html"
      run_once: true