---
- name: Show version on Aruba Switch
  hosts: distswitch_N
  gather_facts: no
  tasks:
    - name: Run show version
      aos_switch_command:
        commands:
          - show version
      register: output

    - debug:
        var: output.stdout
