---
- name: Test Aruba Switch Connectivity
  hosts: distswitch_N
  gather_facts: no
  tasks:
    - name: Run 'show version' on Aruba switch
      arubanetworks.arubaos_switch.arubaoss_command:
        commands:
          - show version
      register: output

    - debug:
        var: output.stdout
