---
- name: Execute Aruba Commands
  hosts: aruba_N1
  gather_facts: no
  tasks:
    - name: Run show running-config
      aruba_command:
        commands:
          - show running-config
      register: config_output

    - name: Display running configuration
      debug:
        var: config_output.stdout_lines
