---
- name: Test Aruba Switch Connectivity
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Run 'show version' on the Aruba device
      ansible.netcommon.cli_command:
        command: "show version"
      register: version_output

    - name: Display device output
      debug:
        var: version_output.stdout_lines
