---
- name: Test Aruba Switch Connectivity
  hosts: all
  gather_facts: no
  tasks:
    - name: Run 'show version' on Aruba switch
      arubanetworks.arubaoss.arubaoss_command:
        commands:
          - show version
      register: output

    - name: Display output
      debug:
        var: output
