---
- name: Test Aruba Switch Connectivity
  hosts: all
  gather_facts: no
  tasks:
    - name: Run 'show version' on the Aruba switch
      aos_switch_command:
        commands:
          - show version
      register: version_output

    - name: Display output
      debug:
        var: version_output.stdout
