---
- name: Test Aruba Switch Connectivity
  hosts: aruba_n17
  gather_facts: no
  tasks:
    - name: Test connection and get basic information
      aruba_command:
        commands:
          - show version
          - show system
          - show vlan
      register: test_output

    - name: Display test results
      debug:
        var: test_output.stdout_lines
